// Homescreen.js
import React from 'react';
import {Button, View, Text, Image} from 'react-native';

export default function AboutScreen({navigation}) {
  return (
    <View style={{flex: 1, alignItems: 'center', justifyContent: 'center'}}>
      <Text>About Screen</Text>
      <Text>
        This is not a normal picture, it was AI generated by Craiyon.com
      </Text>
      <Image source={require('../assets/sunset4.png')} />
      <View style={{flexDirection: 'row'}}>
        <Button
          title="Go to Screen2"
          onPress={() => navigation.navigate('Screen2')}
        />
        <Button
          title="Go Home"
          onPress={() => navigation.navigate('HomeScreen')}
        />
      </View>
    </View>
  );
}
