// Homescreen.js
import React from 'react';
import {Button, View, Text, Image} from 'react-native';

export default function HomeScreen({navigation}) {
  return (
    <View style={{flex: 1, alignItems: 'center', justifyContent: 'center'}}>
      <Text>Screen2</Text>
      <Text>These sunsets were generated by craiyon.com</Text>
      <View style={{flexDirection: 'row'}}>
        <Image source={require('../assets/sunset1.png')} />
        <Image source={require('../assets/sunset2.png')} />
      </View>
      <View style={{flexDirection: 'row'}}>
        <Image source={require('../assets/sunset5.png')} />
        <Image source={require('../assets/sunset6.png')} />
      </View>
      <View style={{flexDirection: 'row'}}>
        <Button
          title="Go to About"
          onPress={() => navigation.navigate('About')}
        />
        <Button
          title="Go Home"
          onPress={() => navigation.navigate('HomeScreen')}
        />
      </View>
    </View>
  );
}
